import { useEffect, useState } from "react";
import {
  Alert, Box, Chip, CircularProgress, Collapse, Divider, Link as MuiLink, Paper, Typography,
} from "@mui/material";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { getDigest } from "../api/client";
import type { DigestIssue } from "../api/types";
import { MONO } from "../theme";
import { useDocumentHead } from "../useDocumentHead";

/**
 * The digest issues.
 *
 * The digest carries changes outward: the portal knows what happened, and the
 * only way to learn it is to visit.
 *
 * The text of an issue is generated from a template over the registry data with
 * no language model, and the reader is told so outright. The difference matters:
 * the portal rests on every claim of its own being checkable, and a text
 * generated by a model would be a claim of the portal that had never been
 * checked. Under the text therefore lie the very records and numbers it was
 * assembled from, and a reader can follow the links and see for themselves.
 */

function LevelMove({ move, onOpen }: {
  move: { technology_id: string; name: string; level_before: string | null; level_after: string };
  onOpen: (id: string) => void;
}) {
  const { t } = useTranslation();
  return (
    <Box sx={{ display: "flex", alignItems: "baseline", gap: 1, py: 0.4 }}>
      <MuiLink
        component="button"
        onClick={() => onOpen(move.technology_id)}
        sx={{ textAlign: "left" }}
      >
        {move.name}
      </MuiLink>
      <Typography variant="caption" sx={{ color: "text.secondary" }}>
        {move.level_before
          ? t("digest.moved", { from: move.level_before, to: move.level_after })
          : t("digest.first", { level: move.level_after })}
      </Typography>
    </Box>
  );
}

/**
 * The grounds of an issue: the records whose change it retells.
 *
 * Collapsed by default. A week's issue fits in a paragraph while the list of
 * records behind it may run to fifty rows, and then the message drowns in its
 * own proof.
 */
function BasisList({ issue, onOpen }: {
  issue: DigestIssue;
  onOpen: (id: string) => void;
}) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  const total = issue.added.length + issue.promoted.length + issue.demoted.length;

  return (
    <Box>
      <MuiLink
        component="button"
        onClick={() => setOpen((v) => !v)}
        sx={{ fontSize: "0.82rem" }}
      >
        {open ? t("digest.hideBasis") : t("digest.showBasis", { count: total })}
      </MuiLink>
      <Collapse in={open}>
        <Box sx={{ mt: 1.5, pl: 1.5, borderLeft: 2, borderColor: "divider" }}>
          {issue.demoted.map((m) => (
            <LevelMove key={`d-${m.technology_id}`} move={m} onOpen={onOpen} />
          ))}
          {issue.promoted.map((m) => (
            <LevelMove key={`p-${m.technology_id}`} move={m} onOpen={onOpen} />
          ))}
          {issue.added.map((m) => (
            <LevelMove key={`a-${m.technology_id}`} move={m} onOpen={onOpen} />
          ))}
        </Box>
      </Collapse>
    </Box>
  );
}

export function DigestPage() {

  const { t, i18n } = useTranslation();
  useDocumentHead({
    title: t("head.digest.title"),
    description: t("head.digest.description"),
  });
  const navigate = useNavigate();
  const [issues, setIssues] = useState<DigestIssue[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getDigest()
      .then((res) => { setIssues(res.issues); setError(null); })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <Box sx={{ p: 4 }}><CircularProgress size={24} /></Box>;
  if (error) return <Box sx={{ p: 4 }}><Alert severity="error">{error}</Alert></Box>;

  return (
    <Box sx={{ maxWidth: 860, mx: "auto", px: 3, py: 4 }}>
      <Typography variant="h4" sx={{ mb: 1 }}>{t("digest.title")}</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 1, maxWidth: "62ch" }}>
        {t("digest.subtitle")}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 4, maxWidth: "62ch" }}>
        {t("digest.provenance")}
      </Typography>

      {issues.length === 0 && (
        <Alert severity="info">{t("digest.empty")}</Alert>
      )}

      {issues.map((issue) => (
        <Paper key={issue.issued_at} variant="outlined" sx={{ p: 3, mb: 2 }}>
          <Box sx={{ display: "flex", alignItems: "baseline", gap: 1.5, mb: 1.5 }}>
            <Typography variant="h6" sx={{ fontFamily: MONO }}>{issue.issued_at}</Typography>
            <Typography variant="caption" color="text.secondary">
              {issue.since
                ? t("digest.period", { since: issue.since })
                : t("digest.firstIssue")}
            </Typography>
          </Box>

          {/*
            An issue is never rewritten, so both texts are born with it. For
            issues published before the localisation there is no English text,
            and the Russian is shown with a note: a blank space is worse than a
            text in the other language, because a blank space does not explain
            itself.
          */}
          <Typography variant="body1" sx={{ mb: 2 }}>
            {i18n.language === "en" ? (issue.text_en || issue.text) : issue.text}
          </Typography>
          {i18n.language === "en" && !issue.text_en && (
            <Typography variant="caption" color="text.secondary" sx={{ display: "block", mb: 2 }}>
              {t("digest.noTranslation")}
            </Typography>
          )}

          {(issue.added.length > 0 || issue.promoted.length > 0 || issue.demoted.length > 0) && (
            <>
              <Divider sx={{ my: 2 }} />
              {/*
                Under the retelling lies what it was assembled from, but
                collapsed: a reader of an issue wants the issue, and a list of
                fifty records pushes it off the screen. For anyone who wants to
                check, opening it costs one click and does not lead away from the
                page.
              */}
              <BasisList
                issue={issue}
                onOpen={(id) => navigate(`/tech/${id}`)}
              />
            </>
          )}

          <Box sx={{ display: "flex", gap: 1, flexWrap: "wrap", mt: 2 }}>
            {issue.evidence_added > 0 && (
              <Chip size="small" variant="outlined"
                    label={t("digest.evidenceChip", { count: issue.evidence_added })} />
            )}
            {issue.links_checked > 0 && (
              <Chip size="small" variant="outlined"
                    label={t("digest.linksChip", { count: issue.links_checked })} />
            )}
            {issue.links_broken > 0 && (
              <Chip size="small" color="warning" variant="outlined"
                    label={t("digest.brokenChip", { count: issue.links_broken })} />
            )}
          </Box>
        </Paper>
      ))}
    </Box>
  );
}
